---
- name: Get stats
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Get number of JT
      ansible.builtin.uri:
        url: https://192.168.1.94/api/v2/metrics/?format=json
        method: GET
        force_basic_auth: true
        user: admin
        password: 'Password1234!'
        return_content: true
        headers:
          Content-Type: application/json
        validate_certs: false
      register: r_test

    - name: Debug
      ansible.builtin.debug:
        msg: 
          #- "{{ r_test }}"
          - "{{ r_test['json']['awx_system_info'] }}"
          - "{{ r_test['json']['awx_job_templates_total'] }}"
          - "{{ r_test['json']['awx_workflow_job_templates_total'] }}"
          - "{{ r_test['json']['awx_license_instance_total'] }}"
          - "{{ r_test['json']['awx_license_instance_free'] }}"

    - name: Get number of JT
      ansible.builtin.uri:
        url: https://192.168.1.94/api/v2/users/?format=json
        method: GET
        force_basic_auth: true
        user: admin
        password: 'Password1234!'
        return_content: true
        headers:
          Content-Type: application/json
        validate_certs: false
      register: r_users
    
    - name: Debug
      ansible.builtin.debug:
        msg: 
          - "{{ ansible_facts }}"
          - "{{ r_users['json']['results'] }}"
          - "{{ r_users['json']['results'][0]['last_login'] | regex_search('[0-9]{4}-[0-9]{2}-[0-9]{2}', '\\0') }}"
          - "{{ ansible_facts['date_time']['date'] }}"
          - "{{ ansible_facts['date_time']['time'] }}"
            #- "{{ ansible_facts['date'] | string }} {{ ansible_facts['time'] | string }}"
          - "{{ ((r_users['json']['results'][0]['last_login'] | regex_search('[0-9]{4}-[0-9]{2}-[0-9]{2}', '\\0') | first | to_datetime) - (ansible_facts['date_time']['date'] | to_datetime('%Y-%m-%d'))).days }}"
            # - "{{ ((_try | to_datetime) - (r_users['json']['results'][0]['last_login'] | regex_search('[0-9]{4}-[0-9]{2}-[0-9]{2}', '\\0') | first | to_datetime('%Y-%m-%d'))).days }}"
      vars:
        _try: "{{ ansible_facts['date'] | string }} {{ ansible_facts['time'] | string }}"

    - name: Test
      ansible.builtin.set_fact:
        active_users: "{{ (active_users | default([])) + [item['last_login']] }}"
        test: "{{ ((item['last_login'] | to_datetime) - (ansible_facts['iso8601_micro'] | to_datetime('%Y-%m-%d %H:%M:%S'))).days  }}"
          #when: _tmp < ansible_facts['iso8601_micro']
      loop: "{{ _tmp2 }}"
      vars:
        test1: "{{ r_users['json']['results'][0]['last_login'] | regex_search('[0-9]{4}-[0-9]{2}-[0-9]{2}', '\\0') }}"
        _tmp2: "{{ r_users['json']['results'] }}"
        _tmp: "{{ r_users['json']['results'] | map(attribute='last_login') }}" 


    - name: Output
      ansible.builtin.debug:
        msg: 
          - "{{ active_users }}"
          - "{{ test }}"

...
