---
- hosts: all
  gather_facts: true
  tasks:
    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx
        state: latest
      notify: nginx

    - name: Ensure nginx config is good
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: nginx

    - name: Ensure index.html is correct
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html

    - name: Ensure test.html is correct
      ansible.builtin.replace:
        path: /var/www/html/test.html
        regexp: ' TeSt '
        replace: ' test '

  handlers:
    - name: nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
...
